export const LOADING = 'LOADING';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const WIFI_REFRESH = 'WIFI_REFRESH';
export const WIFI_LISTED = 'WIFI_LISTED';
export const WIFI_LIST_FAILED = 'WIFI_LIST_FAILED';
export const WIFI_HOME_SELECTED = 'WIFI_HOME_SELECTED';
export const GCM_REGISTERED = 'GCM_REGISTERED';
export const SET_LAST_INITIAL_URL = 'SET_LAST_INITIAL_URL';

//Settings
export const SET_AVATAR = 'SET_AVATAR';
export const SET_NICKNAME = 'SET_NICKNAME';
export const SET_RECEIVE_PUSH = 'SET_RECEIVE_PUSH';

//Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const POP_NOTIFICATION = 'POP_NOTIFICATION';
